name: My First Pipeline

on:
  push:
    branches: [main]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my script
        run: ./check.sh
